# Generated by Django 5.2.4 on 2025-07-29 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('none', 'None'), ('work', 'Work'), ('personal', 'Personal'), ('finance', 'Finance'), ('health', 'Health'), ('study', 'Study'), ('other', 'Other')], default='none', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('reminder', models.CharField(blank=True, choices=[('none', 'None'), ('10min', '10 minutes before'), ('30min', '30 minutes before'), ('1hr', '1 hour before'), ('1day', '1 day before')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
