# Generated by Django 5.2.4 on 2025-08-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('10min', '10 minutes before'), ('15min', '15 minutes before'), ('1hr', '1 hour before'), ('1day', '1 day before')], default='none', max_length=10),
        ),
    ]
