# Generated by Django 5.2.4 on 2025-09-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_planyourtasks_scheduledtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
    ]
