# Generated by Django 5.2.4 on 2025-09-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_scheduledtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='reminder',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('15', '15 minutes before'), ('30', '30 minutes before'), ('60', '1 hour before'), ('1440', '1 day before')], default='none', max_length=10),
        ),
    ]
